#!/bin/bash
# OPT-IN: switch .clangd to ANDROID intellisense (requires the Android NDK).
# Run from project root: ./update_clangd.sh
#
# The DEFAULT .clangd is host-based and needs no NDK. Only run this if you want
# clangd to index the code as an Android build (it defines __ANDROID__, so
# <raymob.h> and the NDK headers get processed).
#
# Steps:
#   1. ./generate_android_commands.sh   -> raymob/.cxx/compile_commands/compile_commands.json
#   2. ./update_clangd.sh               -> rewrites .clangd to use that database
#
# To go back to the host (NDK-free) config:  git checkout -- .clangd

set -e

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CLANGD_PATH="$PROJECT_ROOT/.clangd"
ANDROID_DB="$PROJECT_ROOT/raymob/.cxx/compile_commands/compile_commands.json"

if [ ! -f "$ANDROID_DB" ]; then
  echo "Android compile database not found:"
  echo "  $ANDROID_DB"
  echo ""
  echo "Run ./generate_android_commands.sh first (it needs the Android NDK;"
  echo "set ANDROID_NDK or ANDROID_HOME if it is not auto-detected)."
  exit 1
fi

echo "Switching .clangd to ANDROID intellisense"
echo "  - compile database: raymob/.cxx/compile_commands"

cat >"$CLANGD_PATH" <<EOF
# clangd configuration — ANDROID (opt-in, generated by update_clangd.sh).
# The compile database already carries the NDK target/sysroot/includes.
# To return to the host (NDK-free) config:  git checkout -- .clangd

CompileFlags:
  CompilationDatabase: raymob/.cxx/compile_commands
  Remove:
    - "-fmodules-ts"
    - "-fmodule-mapper=*"
    - "-fdeps-format=*"
    - "-fno-fat-lto-objects"
    - "-flto=*"
EOF

echo ".clangd updated for Android successfully"
