#!/usr/bin/env pwsh
# OPT-IN: switch .clangd to ANDROID intellisense (requires the Android NDK).
# Run from project root: .\update_clangd.ps1
#
# The DEFAULT .clangd is host-based and needs no NDK. Only run this if you want
# clangd to index the code as an Android build (it defines __ANDROID__, so
# <raymob.h> and the NDK headers get processed).
#
# Steps:
#   1. .\generate_android_commands.ps1  -> raymob\.cxx\compile_commands\compile_commands.json
#   2. .\update_clangd.ps1              -> rewrites .clangd to use that database
#
# To go back to the host (NDK-free) config:  git checkout -- .clangd

$ErrorActionPreference = "Stop"

$ProjectRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
$ClangdPath = "$ProjectRoot\.clangd"
$AndroidDb = "$ProjectRoot\raymob\.cxx\compile_commands\compile_commands.json"

if (-not (Test-Path $AndroidDb)) {
    Write-Warning "Android compile database not found:"
    Write-Host "  $AndroidDb"
    Write-Host ""
    Write-Host "Run .\generate_android_commands.ps1 first (it needs the Android NDK;"
    Write-Host "set ANDROID_NDK or ANDROID_HOME if it is not auto-detected)."
    exit 1
}

Write-Host "Switching .clangd to ANDROID intellisense"
Write-Host "  - compile database: raymob\.cxx\compile_commands"

$ClangdContent = @"
# clangd configuration — ANDROID (opt-in, generated by update_clangd.ps1).
# The compile database already carries the NDK target/sysroot/includes.
# To return to the host (NDK-free) config:  git checkout -- .clangd

CompileFlags:
  CompilationDatabase: raymob/.cxx/compile_commands
  Remove:
    - "-fmodules-ts"
    - "-fmodule-mapper=*"
    - "-fdeps-format=*"
    - "-fno-fat-lto-objects"
    - "-flto=*"
"@

Set-Content -Path $ClangdPath -Value $ClangdContent -NoNewline
Write-Host ".clangd updated for Android successfully"
