#!/usr/bin/env python3
"""Turn raylib_multiplatform.toml into everything the build systems need.

The template has four build systems (CMake, Gradle, XcodeGen, GitHub Actions)
and they all need to agree on the same handful of facts: what the game is
called, what its bundle id is, which platforms to build. Left to themselves
they disagree, and the failure is always silent and always expensive — a
release that ships under the wrong identity, or an Android build that quietly
uses a different rres password than the desktop one and cannot read its own
assets.

So there is exactly one hand-written source of truth and one generator. The
build files stay dumb: they read what this wrote, they never parse the config
themselves. Three parsers is three ways to drift.

Nothing this writes is committed — see .gitignore. It is regenerated on every
configure, so it cannot go stale. The price is that Gradle and XcodeGen, which
never invoke CMake, need an explicit `python3 tools/configure.py` step; the CI
workflows have one.

Standard library only. `tomllib` is 3.11+, which the CI image (3.12) and every
supported dev machine have. Pillow is used for icons and is optional — see
generate_icons().

Usage:
    tools/configure.py                     generate everything
    tools/configure.py --check             validate only, write nothing
    tools/configure.py --print-name        the project name
    tools/configure.py --print-targets     JSON array of enabled targets
    tools/configure.py --print-families    JSON array of CI families in play
    tools/configure.py --print-matrix bsd  JSON matrix for one CI family
    tools/configure.py --print-config      the resolved config, as JSON
    tools/configure.py --print-pins        the frozen pins, as key=value
    tools/configure.py --make-default-icon write a placeholder at [icon] source
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import shutil
import sys
import tomllib
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
TOML = REPO / "raylib_multiplatform.toml"
STAMP = REPO / "cmake" / "generated" / "config.stamp"

# Bumped whenever the shape of the generated output changes, so a new generator
# does not silently reuse output produced by an older one.
SCHEMA = 1

GEN_HEADER = "GENERATED by tools/configure.py from raylib_multiplatform.toml — do not edit."


# ---------------------------------------------------------------------------
# Errors
# ---------------------------------------------------------------------------

class ConfigError(Exception):
    """A problem the user must fix in their config, reported without a traceback."""


_warnings: list[str] = []


def warn(msg: str) -> None:
    _warnings.append(msg)
    print(f"configure: warning: {msg}", file=sys.stderr)


# ---------------------------------------------------------------------------
# Targets
# ---------------------------------------------------------------------------

# id -> (CI family, human label). The family decides which reusable workflow
# builds it; ci.yml skips a whole family when none of its targets are enabled.
TARGETS: dict[str, tuple[str, str]] = {
    "linux-x64":     ("linux",   "Linux x86-64"),
    "linux-arm64":   ("linux",   "Linux ARM64"),
    "linux-riscv64": ("linux",   "Linux RISC-V"),
    "windows-x64":   ("windows", "Windows x86-64"),
    "windows-arm64": ("windows", "Windows ARM64"),
    "macos":         ("apple",   "macOS (universal)"),
    "ios":           ("apple",   "iOS (simulator)"),
    "web":           ("web",     "Web (WebAssembly)"),
    "android":       ("android", "Android"),
    "freebsd-x64":   ("bsd",     "FreeBSD x86-64"),
    "freebsd-arm64": ("bsd",     "FreeBSD ARM64"),
    "openbsd-x64":   ("bsd",     "OpenBSD x86-64"),
    "openbsd-arm64": ("bsd",     "OpenBSD ARM64"),
    "netbsd-x64":    ("bsd",     "NetBSD x86-64"),
}

GROUPS: dict[str, list[str]] = {
    "all":     list(TARGETS),
    "linux":   ["linux-x64", "linux-arm64", "linux-riscv64"],
    "windows": ["windows-x64", "windows-arm64"],
    "apple":   ["macos", "ios"],
    "desktop": ["linux-x64", "linux-arm64", "linux-riscv64",
                "windows-x64", "windows-arm64", "macos"],
    "mobile":  ["android", "ios"],
    "bsd":     ["freebsd-x64", "freebsd-arm64",
                "openbsd-x64", "openbsd-arm64", "netbsd-x64"],
    "web":     ["web"],
    "android": ["android"],
}

# The BSD matrix legs, keyed by target id. The OS version is not here: it comes
# from FROZEN_VERSIONS.md, so the weekly canary can float it and the autofix
# agent can bump it (it cannot write files under .github/workflows).
BSD_LEGS: dict[str, dict[str, str]] = {
    "freebsd-x64":   {"os": "freebsd", "arch": "x86-64"},
    "freebsd-arm64": {"os": "freebsd", "arch": "arm64"},
    "openbsd-x64":   {"os": "openbsd", "arch": "x86-64"},
    "openbsd-arm64": {"os": "openbsd", "arch": "arm64"},
    "netbsd-x64":    {"os": "netbsd",  "arch": "x86-64"},
}


def frozen_versions() -> dict[str, str]:
    """The ```versions block of thirdparty/FROZEN_VERSIONS.md.

    Same block tools/versions_check.sh enforces, so the docs, the checker and
    the generator cannot disagree about what is pinned.
    """
    md = REPO / "thirdparty" / "FROZEN_VERSIONS.md"
    out: dict[str, str] = {}
    inside = False
    for line in md.read_text(encoding="utf-8").splitlines():
        if line.strip() == "```versions":
            inside = True
            continue
        if inside and line.strip() == "```":
            break
        if inside:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            parts = line.split(None, 1)
            if len(parts) == 2:
                out[parts[0]] = parts[1].strip()
    if not out:
        raise ConfigError(f"no ```versions block found in {md}")
    return out


def expand_targets(enabled: list[str], disabled: list[str]) -> list[str]:
    """Groups expand and deduplicate, then `disabled` is subtracted.

    Deliberately order-independent and conflict-free: there is no precedence to
    reason about, so `enabled = ["all"], disabled = ["ios"]` means exactly what
    it looks like.
    """
    def resolve(names: list[str], where: str) -> set[str]:
        out: set[str] = set()
        for n in names:
            if n in GROUPS:
                out.update(GROUPS[n])
            elif n in TARGETS:
                out.add(n)
            else:
                known = ", ".join(sorted(set(GROUPS) | set(TARGETS)))
                raise ConfigError(
                    f"[targets] {where}: unknown target or group {n!r}.\nKnown: {known}")
        return out

    result = sorted(resolve(enabled, "enabled") - resolve(disabled, "disabled"),
                    key=list(TARGETS).index)
    if not result:
        raise ConfigError("[targets]: nothing left to build. `enabled` minus `disabled` is empty.")
    return result


def admob_on(cfg: dict, targets: list[str]) -> bool:
    """Is AdMob part of this build?

    Two ways to say no, and the second one is the one nobody remembers to say.
    Turning Android off in [targets] — by name or through a group like
    "mobile" — means there is no Android build to put ads in, so carrying the
    Google Mobile Ads SDK, the AD_ID permission and the Play "advertising ID"
    declaration that comes with it would be paying for nothing.
    """
    return bool(cfg["android"]["admob"]["enabled"]) and "android" in targets


# ---------------------------------------------------------------------------
# Defaults + load
# ---------------------------------------------------------------------------

DEFAULTS: dict = {
    "project": {"name": "ray_test"},
    "window": {"title": "Raylib is Multiplatform!", "width": 800, "height": 450,
               "orientation": "landscape"},
    "targets": {"enabled": ["all"], "disabled": []},
    "android": {
        "application_id": "com.example.raytest",
        "min_sdk": 24, "gl_version": "ES30", "category": "game",
        "display": {"keep_on": True, "immersive": True, "into_cutout": True},
        # Permissions and features are different things and used to be one
        # table, which hid a bug: android:required is an attribute of
        # <uses-feature> only. On a <uses-permission> it is ignored, so
        # internet = false shipped an APK that asked for INTERNET anyway.
        "permissions": {"internet": False, "vibration": False},
        "features": {"gyroscope": False, "accelerometer": False},
        "admob": {"enabled": True,
                  "app_id": "ca-app-pub-3940256099942544~3347511713",
                  "interstitial_id": "ca-app-pub-3940256099942544/1033173712",
                  "rewarded_id": "ca-app-pub-3940256099942544/5224354917"},
    },
    "ios": {"bundle_id": "com.example.raytest", "deployment_target": "15.6", "settings": {}},
    "icon": {"source": "branding/icon.png", "adaptive_background": "#3DDC84"},
    "raylib": {"disabled_modules": []},
    "ui": {"theme": "dark", "font": "", "font_size": 20, "scale": 0,
           "max_elements": 512},
    "dev": {"compiler": "clang", "linker": "auto"},
    "resources": {"rres_password": "raylib-template"},
    "deploy": {"itch": {"user": "", "game": ""},
               "firebase": {"project_id": "",
                            "device": "model=MediumPhone.arm,version=33,"
                                      "locale=en,orientation=portrait"}},
}

EXAMPLE_IDS = {"com.example.raytest", "com.raylib.raymob"}

# The themes rmp::ui ships. A [ui] theme outside this set is a typo that would
# otherwise silently fall back to dark at runtime.
UI_THEMES = {"dark", "light"}


def deep_merge(base: dict, over: dict, path: str = "") -> dict:
    out = dict(base)
    for k, v in over.items():
        here = f"{path}.{k}" if path else k
        if k not in base:
            raise ConfigError(f"unknown key [{here}] in raylib_multiplatform.toml")
        if isinstance(base[k], dict) and isinstance(v, dict):
            # [ios.settings] is a free-form passthrough; do not police its keys.
            out[k] = v if here == "ios.settings" else deep_merge(base[k], v, here)
        else:
            out[k] = v
    return out


def load_config() -> dict:
    if not TOML.exists():
        warn("raylib_multiplatform.toml not found — using defaults.\n"
             "         Create it to name your game and set your app ids. "
             "See README.md.")
        return json.loads(json.dumps(DEFAULTS))
    with TOML.open("rb") as fh:
        try:
            user = tomllib.load(fh)
        except tomllib.TOMLDecodeError as e:
            raise ConfigError(f"raylib_multiplatform.toml is not valid TOML: {e}") from None
    return deep_merge(DEFAULTS, user)


# ---------------------------------------------------------------------------
# Validation
# ---------------------------------------------------------------------------

NAME_RE = re.compile(r"^[A-Za-z][A-Za-z0-9_-]*$")
# Android package rules: dot-separated segments, each starting with a letter.
APPID_RE = re.compile(r"^[a-zA-Z][a-zA-Z0-9_]*(\.[a-zA-Z][a-zA-Z0-9_]*)+$")
# Apple allows hyphens in bundle ids, Android does not.
BUNDLE_RE = re.compile(r"^[a-zA-Z][a-zA-Z0-9-]*(\.[a-zA-Z][a-zA-Z0-9-]*)+$")

PROTECTED_MODULES = {
    "rtextures": "the asset layer (src/rmp/), the rres loader and the CI render gate "
                 "(tests/smoke_test.h calls LoadImageFromScreen) are all built on it",
    "rtext":     "rres-raylib.h calls TextLength from a code path that is always live, so no "
                 "amount of --gc-sections will drop it",
    "rcore":     "mandatory in raylib itself",
    "rlgl":      "mandatory in raylib itself",
}
OPTIONAL_MODULES = {"rshapes", "rmodels", "raudio"}


def validate(cfg: dict, strict_release: bool) -> None:
    name = cfg["project"]["name"]
    if not NAME_RE.match(name):
        raise ConfigError(
            f"[project] name = {name!r} is not usable as a filename.\n"
            "Use letters, digits, '_' and '-', starting with a letter. It becomes the "
            "executable name on five operating systems.")

    if "\n" in cfg["window"]["title"] or "\r" in cfg["window"]["title"]:
        raise ConfigError("[window] title must be a single line: it becomes a Java "
                          ".properties value and an Xcode build setting.")

    orient = cfg["window"]["orientation"]
    if orient not in ("landscape", "portrait", "unspecified"):
        raise ConfigError(f"[window] orientation = {orient!r} must be "
                          "'landscape', 'portrait' or 'unspecified'.")
    for k in ("width", "height"):
        v = cfg["window"][k]
        if not isinstance(v, int) or not (16 <= v <= 16384):
            raise ConfigError(f"[window] {k} = {v!r} must be an integer between 16 and 16384.")

    # android:appCategory, which is how Play files your app. These are the only
    # values Android accepts; anything else makes the manifest merger fail deep
    # inside the Gradle build with a message nobody can act on.
    #
    # This key used to be written into the launcher <intent-filter> instead,
    # where the only value that works is LAUNCHER. Setting it to anything else
    # produced an APK that installed and then had no icon anywhere on the
    # device — see the comment in raymob/app/AndroidManifest.template.xml.
    APP_CATEGORIES = {"game", "audio", "video", "image", "social", "news",
                      "maps", "productivity", "accessibility"}
    category = str(cfg["android"]["category"]).lower()
    if category not in APP_CATEGORIES:
        raise ConfigError(
            f"[android] category = {cfg['android']['category']!r} is not an Android app "
            f"category.\nUse one of: {', '.join(sorted(APP_CATEGORIES))}.\n"
            "It becomes android:appCategory, which is how the Play Store files your app. "
            "It is NOT the launcher intent category — that one is fixed, because an app "
            "without it has no icon.")
    cfg["android"]["category"] = category

    # Every Android switch is a boolean, and TOML will happily hand us the
    # string "false", which is truthy. Java .properties would then receive
    # "false" for a value nobody checked, which is how a switch silently stops
    # switching.
    for table in ("display", "permissions", "features"):
        for k, v in cfg["android"][table].items():
            if not isinstance(v, bool):
                raise ConfigError(f"[android.{table}] {k} = {v!r} must be true or false.")
    if not isinstance(cfg["android"]["admob"]["enabled"], bool):
        raise ConfigError("[android.admob] enabled = "
                          f"{cfg['android']['admob']['enabled']!r} must be true or false.")

    appid = cfg["android"]["application_id"]
    if not APPID_RE.match(appid):
        raise ConfigError(
            f"[android] application_id = {appid!r} is not a valid Android application id.\n"
            "It needs at least one dot and each segment must start with a letter, "
            "e.g. com.yourname.yourgame.")
    # The Gradle preBuild hook rewrites sources by string-substituting this id and
    # reverts them afterwards. A value containing the search string makes the
    # revert non-idempotent and permanently mangles thirdparty/raymob/*.c.
    if "com.raylib.raymob" in appid:
        raise ConfigError(
            f"[android] application_id = {appid!r} must not contain 'com.raylib.raymob'.\n"
            "Gradle rewrites and then reverts that exact string in the raymob sources; "
            "an id containing it corrupts them.")

    bundle = cfg["ios"]["bundle_id"]
    if not BUNDLE_RE.match(bundle):
        raise ConfigError(
            f"[ios] bundle_id = {bundle!r} is not a valid bundle identifier.\n"
            "It needs at least one dot, e.g. com.yourname.yourgame.")

    if not re.match(r"^\d+\.\d+(\.\d+)?$", str(cfg["ios"]["deployment_target"])):
        raise ConfigError(f"[ios] deployment_target = {cfg['ios']['deployment_target']!r} "
                          "must look like \"15.6\".")

    if cfg["android"]["gl_version"] not in ("ES20", "ES30", "ES31", "ES32"):
        raise ConfigError(f"[android] gl_version = {cfg['android']['gl_version']!r} must be one "
                          "of ES20, ES30, ES31, ES32.")

    min_sdk = cfg["android"]["min_sdk"]
    if not isinstance(min_sdk, int) or not (21 <= min_sdk <= 36):
        raise ConfigError(f"[android] min_sdk = {min_sdk!r} must be an integer between 21 and 36.")

    for mod in cfg["raylib"]["disabled_modules"]:
        if mod in PROTECTED_MODULES:
            raise ConfigError(
                f"[raylib] disabled_modules: {mod!r} cannot be disabled — "
                f"{PROTECTED_MODULES[mod]}.")
        if mod not in OPTIONAL_MODULES:
            raise ConfigError(
                f"[raylib] disabled_modules: unknown module {mod!r}. "
                f"Optional modules are: {', '.join(sorted(OPTIONAL_MODULES))}.")

    if cfg["dev"]["compiler"] not in ("clang", "gcc", "default"):
        raise ConfigError("[dev] compiler must be 'clang', 'gcc' or 'default'.")
    if cfg["dev"]["linker"] not in ("auto", "mold", "lld", "default"):
        raise ConfigError("[dev] linker must be 'auto', 'mold', 'lld' or 'default'.")

    bg = cfg["icon"]["adaptive_background"]
    if bg and not re.match(r"^#[0-9a-fA-F]{6}$", bg):
        raise ConfigError(f"[icon] adaptive_background = {bg!r} must be #RRGGBB, or \"\".")

    # These reach the workflows through $GITHUB_OUTPUT as key=value lines, so the
    # charsets are deliberately tight: a newline in any of them would let the
    # config file define arbitrary job outputs.
    for key, value, pattern, shape in (
        ("[deploy.itch] user", cfg["deploy"]["itch"]["user"], r"^[A-Za-z0-9_-]*$", "an itch.io username"),
        ("[deploy.itch] game", cfg["deploy"]["itch"]["game"], r"^[A-Za-z0-9_-]*$", "an itch.io game slug"),
        ("[deploy.firebase] project_id", cfg["deploy"]["firebase"]["project_id"],
         r"^[a-z0-9-]*$", "a GCP project id (lowercase, digits, hyphens)"),
        ("[deploy.firebase] device", cfg["deploy"]["firebase"]["device"],
         r"^[A-Za-z0-9_.,=-]*$", "a gcloud device spec, e.g. model=MediumPhone.arm,version=33"),
    ):
        if not isinstance(value, str) or not re.match(pattern, value):
            raise ConfigError(f"{key} = {value!r} must be {shape}, or \"\".")

    ui = cfg["ui"]
    if ui["theme"] not in UI_THEMES:
        raise ConfigError(f"[ui] theme = {ui['theme']!r} must be one of "
                          f"{', '.join(sorted(UI_THEMES))}. It only picks which one the app "
                          "starts with — rmp::ui::set_theme() changes it at runtime.")
    if not isinstance(ui["font"], str):
        raise ConfigError("[ui] font must be a string; \"\" means raylib's built-in font.")
    if not isinstance(ui["font_size"], int) or not (6 <= ui["font_size"] <= 200):
        raise ConfigError(f"[ui] font_size = {ui['font_size']!r} must be an integer between 6 and 200.")
    if not isinstance(ui["scale"], (int, float)) or isinstance(ui["scale"], bool) \
            or ui["scale"] < 0 or ui["scale"] > 8:
        raise ConfigError(f"[ui] scale = {ui['scale']!r} must be a number between 0 and 8 "
                          "(0 = derive it from [window] and the real window size).")
    if not isinstance(ui["max_elements"], int) or not (16 <= ui["max_elements"] <= 65536):
        raise ConfigError(f"[ui] max_elements = {ui['max_elements']!r} must be an integer between "
                          "16 and 65536. It sizes the layout arena, so a large value costs memory "
                          "on every platform including phones.")

    targets = expand_targets(cfg["targets"]["enabled"], cfg["targets"]["disabled"])

    if cfg["raylib"]["disabled_modules"] and "ios" in targets:
        warn("[raylib] disabled_modules has no effect on iOS: it links the prebuilt "
             "raylib.xcframework from the pinned fork, which is built without these flags.")

    # Strict only where being strict costs nobody anything. A Play application id
    # can never be changed once published, so shipping com.example.* is a mistake
    # you cannot walk back — but failing a plain `cmake --preset debug` over it
    # would ruin clone-and-build.
    if strict_release:
        bad = []
        if appid in EXAMPLE_IDS and "android" in targets:
            bad.append(f"[android] application_id is still the example value {appid!r}")
        if bundle in EXAMPLE_IDS and "ios" in targets:
            bad.append(f"[ios] bundle_id is still the example value {bundle!r}")
        if bad:
            raise ConfigError(
                "refusing to build a release with placeholder identifiers:\n  "
                + "\n  ".join(bad)
                + "\n\nA Google Play application id is PERMANENT: once published you can never "
                  "change it.\nSet real values in raylib_multiplatform.toml before tagging.")


# ---------------------------------------------------------------------------
# Version — from the git tag, never from the file
# ---------------------------------------------------------------------------

def resolve_version() -> tuple[str, int]:
    """(versionName, versionCode).

    Read from GITHUB_REF_NAME rather than `git describe`: actions/checkout
    fetches depth 1 with no tags, so git has nothing to describe. Untagged
    builds get 0.0.0-dev / 1.

    versionCode packs the semver into an always-increasing integer. Pre-release
    tags (v1.2.3-rc1) share the code of their base version, which is fine
    because nothing here uploads to Play automatically.
    """
    ref_type = os.environ.get("GITHUB_REF_TYPE", "")
    ref_name = os.environ.get("GITHUB_REF_NAME", "")
    if ref_type == "tag" and ref_name.startswith("v"):
        # Anchored at both ends, and only a -prerelease/+build suffix may follow.
        # Unanchored, 'v1.2.3.4' matched its own prefix: versionName kept the .4
        # while versionCode silently became 1002003, so v1.2.3.4 and v1.2.3.5
        # would collide and Play would reject the second upload for no visible
        # reason.
        m = re.fullmatch(r"v(\d+)\.(\d+)\.(\d+)(?:[-+][0-9A-Za-z.\-+]*)?", ref_name)
        if m:
            major, minor, patch = (int(g) for g in m.groups())
            if minor > 999 or patch > 999:
                raise ConfigError(
                    f"tag {ref_name!r}: minor and patch must each stay below 1000 so the Android "
                    "versionCode stays monotonic.")
            return ref_name[1:], major * 1_000_000 + minor * 1_000 + patch
        # ci.yml releases on 'v*', so a v-tag that does not parse is on the
        # release path. Falling back would publish a release named 0.0.0-dev.
        raise ConfigError(
            f"tag {ref_name!r} is not vMAJOR.MINOR.PATCH (optionally -rc1 / +build).\n"
            "Releases take their version from the tag and there is no fallback that "
            "would not be a lie.\nDelete the tag and re-tag: git tag -d "
            f"{ref_name} && git push origin :refs/tags/{ref_name}")
    if ref_type == "tag" and ref_name:
        warn(f"tag {ref_name!r} does not start with 'v'; using 0.0.0-dev.")
    return "0.0.0-dev", 1


# ---------------------------------------------------------------------------
# raylib configuration flags
# ---------------------------------------------------------------------------

MODULE_FLAG = {
    "rshapes": "SUPPORT_MODULE_RSHAPES",
    "rtextures": "SUPPORT_MODULE_RTEXTURES",
    "rtext": "SUPPORT_MODULE_RTEXT",
    "rmodels": "SUPPORT_MODULE_RMODELS",
    "raudio": "SUPPORT_MODULE_RAUDIO",
}


def parse_raylib_config() -> dict[str, int]:
    """Read every SUPPORT_* flag and its real value out of raylib's config.h.

    We do NOT use raylib's own CMake options. They only take effect when
    CUSTOMIZE_BUILD=ON, and turning that on flips roughly fifteen flags that are
    `0` in config.h to ON, because cmake/ParseConfigHeader.cmake maps any
    uncommented #define to ON without looking at its value. Defining
    EXTERNAL_CONFIG_FLAGS and supplying the complete set ourselves is the only
    way to get what the config actually says.

    Because we supply the complete set, a flag we fail to parse would be
    undefined, and `#if SUPPORT_X` treats undefined as 0 — silently disabling a
    feature nobody asked to disable. Hence the sanity checks below.
    """
    header = REPO / "thirdparty" / "raylib" / "src" / "config.h"
    if not header.exists():
        raise ConfigError(f"{header} not found (is the raylib submodule checked out?)")

    text = header.read_text(encoding="utf-8", errors="replace")
    start = text.find("#if !defined(EXTERNAL_CONFIG_FLAGS)")
    end = text.find("#endif // !EXTERNAL_CONFIG_FLAGS")
    if start < 0 or end < 0:
        raise ConfigError(
            "could not find the EXTERNAL_CONFIG_FLAGS guard in raylib's config.h. "
            "raylib's layout changed; tools/configure.py needs updating.")
    guarded = text[start:end]

    flags: dict[str, int] = {}
    unrepresentable: list[str] = []
    for line in guarded.splitlines():
        stripped = line.strip()
        if stripped.startswith("//"):
            continue  # commented out: raylib's own sources supply the default
        if not stripped.startswith("#define"):
            continue
        m = re.match(r"#define\s+([A-Za-z_][A-Za-z0-9_]*)\s+(-?\d+)\s*(//.*)?$", stripped)
        if m:
            # Everything inside the guard is passed through, not just SUPPORT_*.
            # Defining EXTERNAL_CONFIG_FLAGS skips the whole block, so a value we
            # fail to carry over (RLGL_SHOW_GL_DETAILS_INFO, say) would silently
            # become 0 and change the engine's behaviour.
            flags[m.group(1)] = int(m.group(2))
            continue
        name = re.match(r"#define\s+([A-Za-z_][A-Za-z0-9_]*)", stripped)
        unrepresentable.append(name.group(1) if name else stripped)

    if unrepresentable:
        raise ConfigError(
            "raylib's config.h defines values inside the EXTERNAL_CONFIG_FLAGS guard that this "
            "generator cannot carry over as integers:\n  " + ", ".join(unrepresentable) +
            "\nUpdate tools/configure.py to pass them through, or they will be silently lost.")

    for required in MODULE_FLAG.values():
        if required not in flags:
            raise ConfigError(f"{required} not found in raylib's config.h — "
                              "raylib's layout changed; tools/configure.py needs updating.")
    return flags


def raylib_defs(cfg: dict) -> tuple[list[str], list[str]]:
    """(compile definitions, extra source files needed to keep the link valid)."""
    flags = parse_raylib_config()
    for mod in cfg["raylib"]["disabled_modules"]:
        flags[MODULE_FLAG[mod]] = 0

    defs = ["EXTERNAL_CONFIG_FLAGS"] + [f"{k}={v}" for k, v in sorted(flags.items())]

    # Disabling raudio leaves the asset layer referencing symbols that no longer
    # exist: assets::LoadSound calls LoadWaveFromMemory, LoadSoundFromWave,
    # UnloadWave and raylib's own LoadSound, and rres-raylib.h compiles audio
    # loaders regardless of which raylib modules are on.
    #
    # GNU ld hides this. It garbage-collects the unreachable sections before it
    # complains, so a Linux build of `disabled_modules = ["raudio"]` links
    # cleanly. Apple's ld64 resolves undefined symbols BEFORE dead-stripping, so
    # the identical config fails on macOS and iOS only. Stubs cost nothing and
    # work on every linker.
    stubs = ["raudio"] if "raudio" in cfg["raylib"]["disabled_modules"] else []
    return defs, stubs


STUB_SOURCE = """/* {header}
 *
 * [raylib] disabled_modules = ["raudio"] removes these from libraylib, but the
 * template's asset layer still refers to them — assets::LoadSound decodes a
 * Wave and turns it into a Sound, and rres-raylib.h compiles audio loaders
 * whatever the module flags say.
 *
 * They have to resolve even though nothing reachable calls them: Apple's ld64
 * errors on undefined symbols before it ever dead-strips them, so without this
 * file the config that links fine on Linux fails on macOS and iOS only.
 *
 * raylib.h supplies the real types, so these cannot drift out of ABI with the
 * declarations they are standing in for.
 */
#include <raylib.h>

Wave LoadWaveFromMemory(const char *fileType, const unsigned char *fileData, int dataSize)
{{
    (void)fileType; (void)fileData; (void)dataSize;
    Wave empty = {{0}};
    return empty;
}}

Sound LoadSoundFromWave(Wave wave)
{{
    (void)wave;
    Sound empty = {{0}};
    return empty;
}}

Sound LoadSound(const char *fileName)
{{
    (void)fileName;
    Sound empty = {{0}};
    return empty;
}}

void UnloadWave(Wave wave)
{{
    (void)wave;
}}
"""


# ---------------------------------------------------------------------------
# Generators
# ---------------------------------------------------------------------------

def write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return
    path.write_text(content, encoding="utf-8")


def cmake_escape(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def gen_cmake(cfg: dict) -> None:
    name = cfg["project"]["name"]
    write(REPO / "cmake" / "generated" / "project.cmake", f"""# {GEN_HEADER}
set(TEMPLATE_PROJECT_NAME "{cmake_escape(name)}")
set(TEMPLATE_RRES_PASSWORD "{cmake_escape(cfg['resources']['rres_password'])}")
""")

    defs, stubs = raylib_defs(cfg)
    stub_path = REPO / "cmake" / "generated" / "module_stubs.c"
    if stubs:
        write(stub_path, STUB_SOURCE.format(header=GEN_HEADER))
    elif stub_path.exists():
        stub_path.unlink()

    lines = [f"# {GEN_HEADER}",
             "#",
             "# The complete flag set, passed with EXTERNAL_CONFIG_FLAGS so raylib's own",
             "# config.h defaults are bypassed. Every flag must be here: `#if SUPPORT_X`",
             "# treats an undefined macro as 0.",
             "set(RAYLIB_CONFIG_DEFS"]
    lines += [f"    {d}" for d in defs]
    lines.append(")")
    lines.append('set(RAYLIB_STUB_SOURCES "{}")'.format(
        '${CMAKE_CURRENT_LIST_DIR}/module_stubs.c' if stubs else ""))
    write(REPO / "cmake" / "generated" / "raylib_flags.cmake", "\n".join(lines) + "\n")

    # Dev toolchain. Only ever included for non-production builds, so CI (which
    # builds `release`/`web`) is untouched by anything in [dev].
    dev = [f"# {GEN_HEADER}",
           "#",
           "# Local development only. The release and web presets never include this.",
           ""]
    compiler = cfg["dev"]["compiler"]
    if compiler != "default":
        cc, cxx = ("clang", "clang++") if compiler == "clang" else ("gcc", "g++")
        dev += [
            f"find_program(_TPL_CC  {cc})",
            f"find_program(_TPL_CXX {cxx})",
            "if(_TPL_CC AND _TPL_CXX)",
            '  set(CMAKE_C_COMPILER   "${_TPL_CC}"  CACHE FILEPATH "" FORCE)',
            '  set(CMAKE_CXX_COMPILER "${_TPL_CXX}" CACHE FILEPATH "" FORCE)',
            "else()",
            f'  message(STATUS "[dev] compiler = {compiler} requested but not found; '
            'using the system default")',
            "endif()",
            "",
        ]
    linker = cfg["dev"]["linker"]
    if linker != "default":
        candidates = {"auto": ["mold", "lld"], "mold": ["mold"], "lld": ["lld"]}[linker]
        dev += [
            "# A faster linker is the single biggest win on an incremental debug build.",
            "# CMAKE_LINKER_TYPE needs CMake 3.29+; the project already requires 3.30.",
            f"foreach(_ld {' '.join(candidates)})",
            "  find_program(_TPL_LD_${_ld} ${_ld})",
            "  if(_TPL_LD_${_ld})",
            "    string(TOUPPER ${_ld} _TPL_LD_TYPE)",
            '    set(CMAKE_LINKER_TYPE ${_TPL_LD_TYPE})',
            '    message(STATUS "[dev] linker: ${_ld}")',
            "    break()",
            "  endif()",
            "endforeach()",
        ]
    write(REPO / "cmake" / "generated" / "dev_toolchain.cmake", "\n".join(dev) + "\n")


def gen_app_config(cfg: dict) -> None:
    w = cfg["window"]
    ui = cfg["ui"]
    write(REPO / "include" / "rmp" / "generated" / "config.h", f"""/* {GEN_HEADER} */
#ifndef APP_CONFIG_H
#define APP_CONFIG_H

#define APP_NAME          "{cfg['project']['name']}"
#define APP_WINDOW_TITLE  "{w['title'].replace('"', chr(92) + chr(34))}"
#define APP_WINDOW_WIDTH  {w['width']}
#define APP_WINDOW_HEIGHT {w['height']}

/* Obfuscation only — this string is in the shipped binary. It lives here
   because Android and iOS never get -DRRES_PASSWORD from their build systems,
   so a value defined only in CMakeLists.txt would silently differ there. */
#define APP_RRES_PASSWORD "{cfg['resources']['rres_password'].replace(chr(92), chr(92) * 2).replace(chr(34), chr(92) + chr(34))}"

/* [ui]. APP_UI_THEME is only which theme the app STARTS with; rmp::ui::set_theme
   changes it at any time. APP_UI_FONT is "" for raylib's built-in font.
   APP_UI_FONT_SIZE is in design units, i.e. at the APP_WINDOW_* resolution
   above: rmp::ui scales it from there. APP_UI_SCALE of 0 means derive the
   scale automatically. */
#define APP_UI_THEME        "{ui['theme']}"
#define APP_UI_FONT         "{ui['font'].replace(chr(92), chr(92) * 2).replace(chr(34), chr(92) + chr(34))}"
#define APP_UI_FONT_SIZE    {ui['font_size']}
#define APP_UI_SCALE        {float(ui['scale'])}f
#define APP_UI_MAX_ELEMENTS {ui['max_elements']}

#endif /* APP_CONFIG_H */
""")


def gen_gradle_properties(cfg: dict, targets: list[str]) -> None:
    """The Android knobs, as a properties file settings.gradle injects.

    It cannot be gradle.properties itself: Gradle reads that during
    initialisation, before settings.gradle is evaluated, so nothing inside
    Gradle could bootstrap it. gradle.properties stays tracked and holds only
    the four lines that must exist before the daemon JVM starts.
    """
    a = cfg["android"]
    name = cfg["project"]["name"]
    version_name, version_code = resolve_version()
    admob = admob_on(cfg, targets)
    props = {
        "projectName": name,
        "app.name": cfg["window"]["title"],
        "app.native_library_name": name,
        "app.application_id": a["application_id"],
        "app.min_sdk": a["min_sdk"],
        "app.category": a["category"],
        "app.orientation": cfg["window"]["orientation"],
        "app.version_name": version_name,
        "app.version_code": version_code,
        "gl.version": a["gl_version"],
        "admob.enabled": str(admob).lower(),
        "admob.app_id": a["admob"]["app_id"],
        "admob.interstitial_id": a["admob"]["interstitial_id"],
        "admob.rewarded_id": a["admob"]["rewarded_id"],
        "display.keep_on": str(a["display"]["keep_on"]).lower(),
        "display.immersive": str(a["display"]["immersive"]).lower(),
        "display.into_cutout": str(a["display"]["into_cutout"]).lower(),
        # Ads need the network. Leaving this to the user would mean an APK that
        # loads no ads and gives no reason why.
        "permissions.internet": str(a["permissions"]["internet"] or admob).lower(),
        "permissions.vibration": str(a["permissions"]["vibration"]).lower(),
        "requirements.gyroscope": str(a["features"]["gyroscope"]).lower(),
        "requirements.accelerometer": str(a["features"]["accelerometer"]).lower(),
    }
    # Java .properties treats a backslash as an escape, so an unescaped one in
    # a window title would silently mangle the Android app label.
    def esc(v) -> str:
        return str(v).replace("\\", "\\\\")

    body = "\n".join(f"{k}={esc(v)}" for k, v in props.items())
    write(REPO / "raymob" / "generated.properties", f"# {GEN_HEADER}\n{body}\n")


MANIFEST_TEMPLATE = REPO / "raymob" / "app" / "AndroidManifest.template.xml"
MANIFEST_OUT = REPO / "raymob" / "app" / "generated" / "AndroidManifest.xml"

IF_RE = re.compile(r"^\s*<!--\s*#if\s+([a-z_]+)\s*-->\s*$")
ENDIF_RE = re.compile(r"^\s*<!--\s*#endif\s*-->\s*$")
DOC_RE = re.compile(r"^\s*<!--\s*#doc\s*-->\s*$")
ENDDOC_RE = re.compile(r"^\s*<!--\s*#enddoc\s*-->\s*$")


def gen_android_manifest(cfg: dict, targets: list[str]) -> None:
    """The Android manifest, with whole elements kept or dropped.

    AGP's manifestPlaceholders substitute *values* inside attributes; they
    cannot remove an element. And an element is exactly what a permission is:
    you either ask for it or you do not, there being no android:required on
    <uses-permission> (that attribute belongs to <uses-feature>, and writing it
    there is silently ignored — which is how internet = false used to ship an
    APK that asked for INTERNET regardless).

    So the conditional blocks are resolved here, before Gradle ever sees the
    file. The syntax is one flag per block, no nesting and no else, because
    anything richer would be a language and this is a manifest.
    """
    a = cfg["android"]
    admob = admob_on(cfg, targets)
    flags = {
        "internet": bool(a["permissions"]["internet"]) or admob,
        "vibration": bool(a["permissions"]["vibration"]),
        "admob": admob,
    }

    out: list[str] = []
    keeping = True
    active: str | None = None
    in_doc = False
    for n, line in enumerate(MANIFEST_TEMPLATE.read_text().splitlines(), 1):
        # #doc ... #enddoc is the template explaining itself. It is for whoever
        # opens the template, not for the manifest Gradle reads.
        if DOC_RE.match(line):
            in_doc = True
            continue
        if ENDDOC_RE.match(line):
            in_doc = False
            continue
        if in_doc:
            continue
        m = IF_RE.match(line)
        if m:
            if active is not None:
                raise ConfigError(f"{MANIFEST_TEMPLATE.name}:{n}: nested #if "
                                  f"({active!r} is still open).")
            active = m.group(1)
            if active not in flags:
                raise ConfigError(f"{MANIFEST_TEMPLATE.name}:{n}: unknown flag "
                                  f"{active!r}. Known: {', '.join(sorted(flags))}.")
            keeping = flags[active]
            continue
        if ENDIF_RE.match(line):
            if active is None:
                raise ConfigError(f"{MANIFEST_TEMPLATE.name}:{n}: #endif without #if.")
            active = None
            keeping = True
            continue
        if keeping:
            out.append(line)
    if active is not None:
        raise ConfigError(f"{MANIFEST_TEMPLATE.name}: #if {active} was never closed.")
    if in_doc:
        raise ConfigError(f"{MANIFEST_TEMPLATE.name}: #doc was never closed.")

    # Dropping a block leaves the blank lines that surrounded it behind.
    tidy: list[str] = []
    for line in out:
        if not line.strip() and (not tidy or not tidy[-1].strip()):
            continue
        tidy.append(line)

    # The XML declaration has to stay the very first thing in the file, so the
    # generated-by notice goes after it rather than on top.
    if tidy and tidy[0].startswith("<?xml"):
        tidy.insert(1, f"<!-- {GEN_HEADER} -->")
    else:
        tidy.insert(0, f"<!-- {GEN_HEADER} -->")

    write(MANIFEST_OUT, "\n".join(tidy).rstrip() + "\n")


def yaml_scalar(v) -> str:
    if isinstance(v, bool):
        return "YES" if v else "NO"
    if isinstance(v, (int, float)):
        return str(v)
    s = str(v)
    if s == "" or re.search(r'[:#\[\]{}",\'\n]', s) or s != s.strip():
        return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'
    return s


def gen_ios_project(cfg: dict) -> None:
    name = cfg["project"]["name"]
    ios = cfg["ios"]
    dt = ios["deployment_target"]
    version_name, _ = resolve_version()
    orientations = {
        "landscape": "UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight",
        "portrait": "UIInterfaceOrientationPortrait",
        "unspecified": ("UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft "
                        "UIInterfaceOrientationLandscapeRight"),
    }[cfg["window"]["orientation"]]

    extra = "".join(f"        {k}: {yaml_scalar(v)}\n" for k, v in ios["settings"].items())
    icon = ""
    if (REPO / "ios" / "Assets.xcassets" / "AppIcon.appiconset" / "Contents.json").exists():
        icon = ("      - path: Assets.xcassets\n"
                "        buildPhase: resources\n")

    write(REPO / "ios" / "project.yml", f"""# {GEN_HEADER}
#
#   cd ios && xcodegen generate
#   xcodebuild -project {name}.xcodeproj -scheme {name} \\
#       -destination 'generic/platform=iOS Simulator' CODE_SIGNING_ALLOWED=NO build
#
# Wires the game sources + rres + the pinned raylib-iOS fork
# (raylib.xcframework) + the bundled ANGLE frameworks. Device builds
# additionally need a signing team — set it in [ios.settings] in
# raylib_multiplatform.toml.

name: {name}
options:
  bundleIdPrefix: {ios['bundle_id'].rsplit('.', 1)[0]}
  createIntermediateGroups: true
  deploymentTarget:
    iOS: "{dt}"

settings:
  base:
    IPHONEOS_DEPLOYMENT_TARGET: "{dt}"

targets:
  {name}:
    type: application
    platform: iOS
    deploymentTarget: "{dt}"
    sources:
      - path: ../src
      - path: ../include
      # Folder reference (not a group): the whole directory is copied into the
      # bundle as `resources/`, so RESOURCES_PATH="./resources/" resolves once
      # the app chdir's to its bundle (see RMP_IOS_FUNCS in rmp/app.h).
      # Without this the app builds and boots but every LoadTexture returns 0x0.
      - path: ../resources
        type: folder
        buildPhase: resources
{icon}    dependencies:
      - framework: ../thirdparty/raylib-ios/raylib.xcframework
        embed: false
      - framework: ../thirdparty/raylib-ios/deps/ANGLE/libEGL.xcframework
        embed: true
      - framework: ../thirdparty/raylib-ios/deps/ANGLE/libGLESv2.xcframework
        embed: true
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: {ios['bundle_id']}
        PRODUCT_NAME: {name}
        MARKETING_VERSION: "{version_name}"
        # Info.plist is generated by Xcode from these keys
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_CFBundleDisplayName: {yaml_scalar(cfg['window']['title'])}
        INFOPLIST_KEY_UILaunchStoryboardName: ""
        INFOPLIST_KEY_UIRequiresFullScreen: YES
        INFOPLIST_KEY_UIStatusBarHidden: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations: {orientations}
        INFOPLIST_KEY_UIRequiredDeviceCapabilities: arm64
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        {'ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon' if icon else '# no app icon generated'}
        # raylib iOS backend
        GCC_PREPROCESSOR_DEFINITIONS:
          - PLATFORM_IOS
          - GRAPHICS_API_OPENGL_ES3
          # Escaped quotes so RESOURCES_PATH expands to a real string literal
          - RESOURCES_PATH=\\"./resources/\\"
        CLANG_CXX_LANGUAGE_STANDARD: c++20
        CLANG_CXX_LIBRARY: libc++
        HEADER_SEARCH_PATHS:
          - $(SRCROOT)/../include
          - $(SRCROOT)/../tests
          - $(SRCROOT)/../thirdparty/raylib-ios/src
          - $(SRCROOT)/../thirdparty/raylib-ios/projects/Xcode26/raylib/bridge
          - $(SRCROOT)/../thirdparty/rres
          - $(SRCROOT)/../thirdparty/raymob
          - $(SRCROOT)/../thirdparty/clay
{extra}""")


# ---------------------------------------------------------------------------
# Icons
# ---------------------------------------------------------------------------

# Android launcher densities. Legacy icons are 48dp, adaptive foregrounds 108dp.
DENSITIES = {"mdpi": 1.0, "hdpi": 1.5, "xhdpi": 2.0, "xxhdpi": 3.0, "xxxhdpi": 4.0}


def png_size(path: Path) -> tuple[int, int]:
    """Width and height straight out of the IHDR chunk. No dependencies."""
    data = path.read_bytes()[:33]
    if data[:8] != b"\x89PNG\r\n\x1a\n" or data[12:16] != b"IHDR":
        raise ConfigError(f"[icon] {path.name} is not a PNG.")
    return (int.from_bytes(data[16:20], "big"), int.from_bytes(data[20:24], "big"))


def generate_ios_icon(cfg: dict, src: Path) -> None:
    """The iOS app icon, without Pillow.

    Since Xcode 14 a single 1024x1024 image is a complete AppIcon — Xcode
    derives every other size. So this is a file copy, not a resize, which means
    iOS icons work on a macOS runner that has no image library at all. Only
    Android needs real resampling.
    """
    appicon = REPO / "ios" / "Assets.xcassets" / "AppIcon.appiconset"
    w, h = png_size(src)
    if w != h:
        raise ConfigError(f"[icon] {cfg['icon']['source']} is {w}x{h}; it must be square.")
    if w != 1024:
        warn(f"[icon] {cfg['icon']['source']} is {w}x{w}; the App Store requires exactly "
             "1024x1024. Simulator builds will still work.")
    appicon.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(src, appicon / "icon-1024.png")
    (appicon / "Contents.json").write_text(json.dumps({
        "images": [{"filename": "icon-1024.png", "idiom": "universal",
                    "platform": "ios", "size": "1024x1024"}],
        "info": {"author": "xcode", "version": 1},
    }, indent=2) + "\n")
    (REPO / "ios" / "Assets.xcassets" / "Contents.json").write_text(
        json.dumps({"info": {"author": "xcode", "version": 1}}, indent=2) + "\n")


def generate_icons(cfg: dict, required: bool) -> None:
    src = REPO / cfg["icon"]["source"]
    res = REPO / "raymob" / "app" / "src" / "main" / "res"

    if not src.exists():
        warn(f"[icon] source = {cfg['icon']['source']!r} not found; keeping whatever icons exist.")
        return

    generate_ios_icon(cfg, src)

    # Skip the work when the inputs have not moved. Also the graceful path for a
    # dev machine without Pillow: as long as the icon is unchanged, nobody needs it.
    # Not in res/: that is an Android resource directory with a strict layout,
    # and a stray file there is one AAPT version away from an error.
    marker = REPO / "cmake" / "generated" / "icon.stamp"
    marker.parent.mkdir(parents=True, exist_ok=True)
    want = hashlib.sha256(
        src.read_bytes() + cfg["icon"]["adaptive_background"].encode()).hexdigest()
    if marker.exists() and marker.read_text().strip() == want:
        return

    try:
        from PIL import Image, ImageDraw
    except ImportError:
        # Only Android and iOS consume the generated icons, and those two jobs
        # ask for them explicitly. Everywhere else — the lint job, a macOS or
        # Windows runner, a contributor's laptop — a missing Pillow must not
        # stop the build over an asset that platform will never look at.
        msg = ("[icon] resources/icon.png changed but Pillow is not installed, so the "
               "ANDROID launcher icons cannot be regenerated.\n"
               "  pip install pillow      (or: apt install python3-pil)\n"
               "(iOS is unaffected — its icon is a copy, not a resize.)")
        if required:
            raise ConfigError(msg) from None
        warn(msg + "\n         Skipping — this only matters for Android and iOS builds.")
        return

    source = Image.open(src).convert("RGBA")
    if source.width != source.height:
        raise ConfigError(f"[icon] {cfg['icon']['source']} is {source.width}x{source.height}; "
                          "it must be square.")
    if source.width < 512:
        warn(f"[icon] {cfg['icon']['source']} is only {source.width}px; "
             "1024x1024 is recommended or the largest densities will look soft.")

    def scaled(px: int) -> "Image.Image":
        return source.resize((px, px), Image.LANCZOS)

    def circular(px: int) -> "Image.Image":
        # Supersample the mask so the edge is smooth rather than stair-stepped.
        img = scaled(px)
        mask = Image.new("L", (px * 4, px * 4), 0)
        ImageDraw.Draw(mask).ellipse((0, 0, px * 4 - 1, px * 4 - 1), fill=255)
        img.putalpha(mask.resize((px, px), Image.LANCZOS))
        return img

    def adaptive_foreground(px: int) -> "Image.Image":
        # Android crops adaptive icons to the centre ~66%, so the artwork has to
        # be inset or the launcher will clip it.
        canvas = Image.new("RGBA", (px, px), (0, 0, 0, 0))
        inner = int(px * 0.66)
        canvas.paste(scaled(inner), ((px - inner) // 2, (px - inner) // 2))
        return canvas

    for density, factor in DENSITIES.items():
        d = res / f"mipmap-{density}"
        d.mkdir(parents=True, exist_ok=True)
        scaled(int(48 * factor)).save(d / "ic_launcher.png")
        circular(int(48 * factor)).save(d / "ic_launcher_round.png")
        adaptive_foreground(int(108 * factor)).save(d / "ic_launcher_foreground.png")

    scaled(512).save(REPO / "raymob" / "app" / "src" / "main" / "ic_launcher-playstore.png")

    anydpi = res / "mipmap-anydpi-v26"
    anydpi.mkdir(parents=True, exist_ok=True)
    bg = cfg["icon"]["adaptive_background"]
    background = ("@color/ic_launcher_background" if bg else "@mipmap/ic_launcher_foreground")
    adaptive = ('<?xml version="1.0" encoding="utf-8"?>\n'
                '<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">\n'
                f'    <background android:drawable="{background}"/>\n'
                '    <foreground android:drawable="@mipmap/ic_launcher_foreground"/>\n'
                '</adaptive-icon>\n')
    (anydpi / "ic_launcher.xml").write_text(adaptive)
    (anydpi / "ic_launcher_round.xml").write_text(adaptive)

    values = res / "values"
    values.mkdir(parents=True, exist_ok=True)
    (values / "ic_launcher_background.xml").write_text(
        '<?xml version="1.0" encoding="utf-8"?>\n<resources>\n'
        f'    <color name="ic_launcher_background">{bg or "#000000"}</color>\n</resources>\n')

    marker.write_text(want + "\n")


def make_default_icon(dest: Path) -> None:
    """Draw the placeholder icon shipped with the template, at [icon] source.

    The destination follows the config rather than being hardcoded to
    branding/icon.png: the folder is the user's to rename, and writing the
    placeholder somewhere the build is not looking would be worse than not
    writing it at all."""
    from PIL import Image, ImageDraw
    size = 1024
    img = Image.new("RGBA", (size, size), (26, 28, 44, 255))
    d = ImageDraw.Draw(img)
    d.rounded_rectangle((140, 140, size - 140, size - 140), radius=90,
                        outline=(245, 245, 245, 255), width=44)
    d.rounded_rectangle((330, 330, size - 330, size - 330), radius=40,
                        fill=(230, 69, 57, 255))
    dest.parent.mkdir(parents=True, exist_ok=True)
    img.save(dest)
    print(f"wrote {dest.relative_to(REPO)}")


# ---------------------------------------------------------------------------
# Stamp
# ---------------------------------------------------------------------------

def compute_stamp() -> str:
    """Content hash of every input CMake needs to decide whether to regenerate.

    Content, not mtimes: cross-platform-actions rsyncs the workspace into the
    BSD VMs and timestamps do not survive that reliably.
    """
    h = hashlib.sha256()
    h.update(f"schema={SCHEMA}\n".encode())
    for p in (TOML, Path(__file__), REPO / "thirdparty" / "raylib" / "src" / "config.h"):
        h.update(p.read_bytes() if p.exists() else b"<missing>")
    # The version lands inside generated.properties and project.yml.
    h.update("|".join(map(str, resolve_version())).encode())
    return h.hexdigest()


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def _print_matrix(cfg: dict, family: str) -> None:
    targets = expand_targets(cfg["targets"]["enabled"], cfg["targets"]["disabled"])
    if family != "bsd":
        raise ConfigError(f"--print-matrix: only 'bsd' has a matrix (got {family!r})")
    pins = frozen_versions()
    include = []
    for t in targets:
        if t not in BSD_LEGS:
            continue
        leg = dict(BSD_LEGS[t], target=t)
        key = leg["os"]
        if key not in pins:
            raise ConfigError(f"FROZEN_VERSIONS.md has no `{key}` entry, "
                              "which the BSD matrix needs for its OS version.")
        leg["version"] = pins[key]
        include.append(leg)
    print(json.dumps({"include": include}, separators=(",", ":")))


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="validate only, write nothing")
    ap.add_argument("--strict-release", action="store_true",
                    help="also reject placeholder identifiers (used on tag builds)")
    ap.add_argument("--print-name", action="store_true")
    ap.add_argument("--print-targets", action="store_true")
    ap.add_argument("--print-families", action="store_true",
                    help="CI families with at least one enabled target")
    ap.add_argument("--print-matrix", metavar="FAMILY")
    ap.add_argument("--print-config", action="store_true")
    ap.add_argument("--print-stamp", action="store_true")
    ap.add_argument("--print-pins", action="store_true",
                    help="the ```versions block as key=value, for $GITHUB_OUTPUT")
    ap.add_argument("--print-deploy", action="store_true",
                    help="[deploy] as key=value, for $GITHUB_OUTPUT")
    ap.add_argument("--make-default-icon", action="store_true")
    ap.add_argument("--require-icons", action="store_true",
                    help="fail if the icons cannot be generated (Android/iOS jobs)")
    args = ap.parse_args(argv)

    cfg = load_config()
    if args.make_default_icon:
        make_default_icon(REPO / cfg["icon"]["source"])
        return 0

    validate(cfg, strict_release=args.strict_release)
    targets = expand_targets(cfg["targets"]["enabled"], cfg["targets"]["disabled"])

    if args.print_name:
        print(cfg["project"]["name"])
        return 0
    if args.print_targets:
        print(json.dumps(targets, separators=(",", ":")))
        return 0
    if args.print_families:
        print(json.dumps(sorted({TARGETS[t][0] for t in targets}), separators=(",", ":")))
        return 0
    if args.print_matrix:
        _print_matrix(cfg, args.print_matrix)
        return 0
    if args.print_pins:
        for k, v in frozen_versions().items():
            print(f"{k}={v}")
        return 0
    if args.print_deploy:
        dep = cfg["deploy"]
        for k, v in (("itch_user", dep["itch"]["user"]),
                     ("itch_game", dep["itch"]["game"]),
                     ("firebase_project", dep["firebase"]["project_id"]),
                     ("firebase_device", dep["firebase"]["device"])):
            print(f"{k}={v}")
        return 0
    if args.print_stamp:
        print(compute_stamp())
        return 0
    if args.print_config:
        version_name, version_code = resolve_version()
        print(json.dumps({
            "config": cfg, "targets": targets,
            "families": sorted({TARGETS[t][0] for t in targets}),
            "version_name": version_name, "version_code": version_code,
        }, indent=2, sort_keys=True))
        return 0
    if args.check:
        print(f"configure: OK — {cfg['project']['name']}, {len(targets)} target(s)")
        return 0

    gen_cmake(cfg)
    gen_app_config(cfg)
    gen_gradle_properties(cfg, targets)
    gen_android_manifest(cfg, targets)
    generate_icons(cfg, required=args.require_icons)
    gen_ios_project(cfg)   # after icons: it references the asset catalog if present
    STAMP.parent.mkdir(parents=True, exist_ok=True)
    STAMP.write_text(compute_stamp() + "\n")

    version_name, _ = resolve_version()
    print(f"configure: {cfg['project']['name']} {version_name} — "
          f"{len(targets)} target(s): {' '.join(targets)}")
    if _warnings:
        # Repeated at the end because the individual warnings scroll past in the
        # middle of CMake's own output, where nobody sees them.
        print(f"configure: {len(_warnings)} warning(s) above", file=sys.stderr)
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main(sys.argv[1:]))
    except ConfigError as exc:
        print(f"\nconfigure: error: {exc}\n", file=sys.stderr)
        sys.exit(1)
