# --- the game's own tests (doctest) ------------------------------------------
# Every tests/game/*.cpp, built together with the game's sources -- every .cpp
# and .c under src/ but main.cpp and src/rmp/ -- into game_test, which runs
# with no window: `rmp test unit` builds and runs it, and so does CI's lint
# job. `rmp new` writes one, a test of the main menu; a game that deletes
# tests/game/ has no target, and nothing asks for one. The framework has the
# same folder and builds the same target, so the copy every game starts from
# is tested on every `rmp test`.
#
#   cmake --preset debug -DBUILD_TESTS=ON && cmake --build build --target game_test
#   ./build/game_test -tc="*menu*"
#
# main.cpp stays out because RMP_GAME there is the game's main(). main() here
# is doctest's, written below, so a file in tests/game/ holds TEST_CASEs and
# nothing else. app.cpp comes in because a scene calls rmp::app::quit(), and
# it asks for the symbol RMP_GAME emits (the guard in src/rmp/app.cpp); this
# program's entry point is doctest's main(), so the same file answers it.
if(BUILD_TESTS AND TARGET rmp)
  file(GLOB _rmp_game_tests CONFIGURE_DEPENDS "${CMAKE_CURRENT_SOURCE_DIR}/tests/game/*.cpp")
endif()
if(BUILD_TESTS AND TARGET rmp AND _rmp_game_tests)
  file(GLOB_RECURSE _rmp_game_test_sources CONFIGURE_DEPENDS
    "${CMAKE_CURRENT_SOURCE_DIR}/src/*.cpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/src/*.c"
  )
  list(FILTER _rmp_game_test_sources EXCLUDE REGEX "/src/rmp/")
  list(REMOVE_ITEM _rmp_game_test_sources "${CMAKE_CURRENT_SOURCE_DIR}/src/main.cpp")
  # CONFIGURE rather than WRITE: it touches the file only when the text
  # changes, so a reconfigure does not recompile doctest's main every time.
  file(CONFIGURE OUTPUT "${CMAKE_BINARY_DIR}/game_test_main.cpp" @ONLY CONTENT
"// GENERATED by cmake/game_tests.cmake: the main() of game_test, which is doctest's.
#define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN
#include <doctest.h>

// src/rmp/app.cpp asks for this symbol so that a program with no entry point
// is a link error that names it. This program's entry point is the main()
// above.
extern \"C\" void rmp_entry_point_is_declared_exactly_once() {}
")
  add_executable(game_test ${_rmp_game_tests} ${_rmp_game_test_sources}
    "${CMAKE_BINARY_DIR}/game_test_main.cpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/src/rmp/app.cpp")
  set_property(TARGET game_test PROPERTY CXX_STANDARD 20)
  # SYSTEM for doctest, as for unit_test. src/ so a test includes a scene the
  # way src/main.cpp does: "scenes/main_menu.h".
  target_include_directories(game_test SYSTEM PRIVATE
    "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/doctest")
  target_include_directories(game_test PRIVATE "${CMAKE_CURRENT_SOURCE_DIR}/src")
  target_compile_definitions(game_test PRIVATE RMP_RESOURCES_PATH="${RESOURCES_PATH}")
  target_link_libraries(game_test PRIVATE rmp)
  rmp_apply_compile_flags(game_test)
endif()
